KIT-274 add patch position for link
WildCodeSchool/bugs-squad-project-backend pull request #22
Opened 2023-07-20 07:36 UTC by emericb

2023-07-20 12:17 UTC, Benja-san requested changes

2023-07-20 12:17 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/CollectionController.java
> +        System.out.println("link:" + links.get(0).getId());
remove debug printing

2023-07-20 12:27 UTC, emericb commented on src/main/java/com/templateproject/api/controller/CollectionController.java
> +        System.out.println("link:" + links.get(0).getId());
done

2023-07-24 12:38 UTC, Benja-san approved these changes

2023-07-24 12:41 UTC, Tylyfox approved these changes

2023-07-24 12:41 UTC, merged