K it 148 mailer & contact form
WildCodeSchool/bugs-squad-project-backend pull request #7
Opened 2023-07-04 09:14 UTC by MatteiT

2023-07-04 09:25 UTC, emericb requested changes

2023-07-04 09:25 UTC, emericb commented on src/main/java/com/templateproject/api/entity/Contact.java
Remove setId for primary

2023-07-04 09:29 UTC, emericb approved these changes

2023-07-04 11:37 UTC, Benja-san requested changes

2023-07-04 11:37 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/ContactController.java
> +        Contact contactEnregistre = contactService.enregistrerContact(contact);
english variable names

2023-07-04 11:37 UTC, Benja-san commented on src/main/java/com/templateproject/api/service/ContactService.java
> +    public Contact enregistrerContact(Contact contact) {
english variable name

2023-07-04 11:37 UTC, Benja-san commented on src/main/java/com/templateproject/api/service/EmailService.java
> +        // Mail pour l'administrateur
remove dead code

2023-07-04 11:37 UTC, Benja-san commented on src/main/resources/application.properties
> +spring.mail.username=BugsSquadInd
put those sensitive datas inside application-dev.properties!

2023-07-04 11:50 UTC, emericb approved these changes

2023-07-04 14:46 UTC, emericb approved these changes

2023-07-05 07:25 UTC, Benja-san approved these changes

2023-07-05 07:27 UTC, merged