Kit 158 - CRUD todolists
WildCodeSchool/bugs-squad-project-backend pull request #9
Opened 2023-07-04 13:44 UTC by emmirose

2023-07-04 14:45 UTC, emericb approved these changes

2023-07-05 07:53 UTC, Benja-san requested changes

2023-07-05 07:53 UTC, Benja-san commented on src/main/java/com/templateproject/api/entity/Task.java
> +  public Task() {
If a Task needs at least a description, create a second constructor with description as a parameter

2023-07-05 07:53 UTC, Benja-san commented on src/main/java/com/templateproject/api/entity/ToDoList.java
> +    public ToDoList() {
Here a Task will at least have a title, create a constructor with title (and any other necessaries parameters to construct or hydrate the object)

2023-07-05 07:53 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/TaskController.java
> +  public Task updateTask(@PathVariable(value = "id") Long id, @RequestBody Task task) {
This method is not working, you are retrieving with the PathVariable only the "id" wildCard (corresponding to list id) and then find a task with it. this method needs to be reshaped

2023-07-05 07:53 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/ToDoListController.java
> +    return toDoListRepository.findById(id).orElse(null);
It would maybe be better to send an exception instead of null ?

2023-07-05 07:53 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/TaskController.java
> +    return task.orElse(null);
It would maybe be better to send an exception instead of null ?

2023-07-06 07:20 UTC, emericb approved these changes

2023-07-06 09:20 UTC, Benja-san approved these changes

2023-07-06 09:22 UTC, merged